openapi: 3.0.4
info:
  title: User Agent Generator
  description: >-
    User Agent Generator is a simple tool for generating user agent strings. It
    returns a random user agent string.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/useragentgenerator:
    get:
      summary: Generate User Agent
      description: Generate a random user agent string
      operationId: useragentgenerator
      parameters:
        - name: device
          in: query
          schema:
            type: string
          required: true
          description: The device type for the user agent string
          example: desktop
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  ua: >-
                    Mozilla/5.0 (Windows NT 6.4) AppleWebKit/537.36.0 (KHTML,
                    like Gecko) Chrome/94.0.0.0 Safari/537.36.0
                  browser:
                    name: Chrome
                    version: 94.0.0.0
                    major: '94'
                  engine:
                    name: Blink
                    version: 94.0.0.0
                  os:
                    name: Windows
                    version: '10'
                  device: {}
                  cpu: {}
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
